version: '3.8'

services:

  mysql:
    image: mysql:8
    #container_name: mysql_student
    environment:
      MYSQL_ROOT_PASSWORD: Root@1234
      MYSQL_DATABASE: studentdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    #container_name: student_app
    ports:
      - "8089:8080"
    depends_on:
      - mysql
    environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studentdb
      #SPRING_DATASOURCE_USERNAME: root
      #SPRING_DATASOURCE_PASSWORD: Root@1234

      DB_URL: jdbc:mysql://mysql:3306/studentdb
      DB_USER: root
      DB_PASS: Root@1234

volumes:
  mysql_data:
